[package]
name = "defs"
version = "0.1.0"
authors = ["uint256_t"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-quote = "0.3.0"
proc-macro-error = "1.0.0"

[lib]
proc-macro = true

