[package]
name = "cilk"
version = "0.1.1"
authors = ["uint256_t"]
edition = "2018"

[dependencies]
rustc-hash = "1.0.1"
id-arena = "2.2.1"
dynasm = "0.3.2"
dynasmrt = "0.3.1"
defs = { path = "defs", version = "0.1.0" }

