[package]
name = "cilk"
version = "0.2.0"
authors = ["uint256_t"]
edition = "2018"

[dependencies]
rustc-hash = "1.0.1"
id-arena = "2.2.1"
dynasm = "0.3.2"
dynasmrt = "0.3.1"
lazy_static = "1.4.0"
bitvec = "0.17.4"
defs = { path = "defs", version = "0.1.0" }

