version: 2

jobs:
  build:
    docker:
      - image: ubuntu

    working_directory: /opt/rucc

    steps:
      - checkout

      - run:
          command: apt-get update

      - run:
          command: apt-get install -y zlib1g-dev wget clang

      - run:
          command: |
            wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
            chmod +x rustup-init
            ./rustup-init -y --no-modify-path --default-toolchain nightly-2019-07-10-x86_64-unknown-linux-gnu
            RUSTUP_HOME=~/.cargo/bin/rustup
            CARGO_HOME=~/.cargo/bin/cargo
            chmod -R a+w $RUSTUP_HOME $CARGO_HOME;
            rm rustup-init
            source ~/.cargo/env

      - run:
          name: Test and Coverage
          command: |
            export PATH=~/.cargo/bin:$PATH
            RUSTFLAGS='-C link-dead-code -C link-args=-lffi' cargo test
